# Generated by Django 5.1.3 on 2026-01-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_appraisalreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="appraisalreport",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appraisalreport",
            name="user_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appraisalreport",
            name="validation_log",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
