# Generated by Django 5.1.3 on 2026-02-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_contactmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="appraisalreport",
            name="status",
            field=models.CharField(default="Completed", max_length=50),
        ),
    ]
