"""
Django settings for appraisal_project project.

Generated by "django-admin startproject" using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path


import os

BASE_DIR = Path(__file__).resolve().parent.parent


APIKEY = os.environ.get("APIKEY", os.environ.get("GEMINI_API_KEY", ""))

SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-zx9!0$38f(!jbn(7=-m-4gc)ixt8lq&-37=mau-qikbw+kkm5+")
DEBUG = True

ALLOWED_HOSTS = ["*"]


INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "api",
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
]

ROOT_URLCONF = "appraisal_review.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "appraisal_review.wsgi.application"


import os

IS_PRODUCTION = os.environ.get('PYTHONANYWHERE_DOMAIN') is not None

if IS_PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'strdjrbservices$AppraisalReviewData',
            'USER': 'strdjrbservices',
            'PASSWORD': 'Kjg(mB=:r7ju8V2',
            'HOST': 'strdjrbservices.mysql.pythonanywhere-services.com',
            'PORT': '3306',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

# This is the directory where `collectstatic` will gather all static files.
STATIC_ROOT = BASE_DIR / "staticfiles"

# This tells Django not to look in any extra directories for static files.
STATICFILES_DIRS = []


# --- Media Files Settings (for user-uploaded content) ---
# URL to access the media files in the browser
MEDIA_URL = "/media/"

# Path where media files are stored on the filesystem
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- REST Framework and JWT Settings ---
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    )
}

# --- CORS & CSRF Settings ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "https://prod-pramaan.vercel.app",
    "https://qa-pramaan.vercel.app",
    "https://dev-pramaan.vercel.app",
    "https://scaling-fiesta-pjq495j9j669f9967-3000.app.github.dev",
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "https://praman-strdjrbservices.pythonanywhere.com",
    "https://prod-pramaan.vercel.app",
    "https://qa-pramaan.vercel.app",
    "https://dev-pramaan.vercel.app",
    "http://localhost:3000",
    "http://localhost:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
]

# --- Jazzmin Settings ---
JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Appraisal Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Appraisal Project",

    # Logo to use for your site, must be present in static files, used for login form
    "site_logo": None, # e.g. "books/img/logo.png"

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Appraisal Admin",

    # Copyright on the footer
    "copyright": "Appraisal Services Inc.",

       # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},
    ],

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": None,
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,

    "theme": "flatly",

    "order_with_respect_to": ["api", "api.AppraisalReport", "api.UploadedFile", "auth"],

    # Custom links to show on the admin dashboard.
    # Each link has a name, a URL, and an optional icon from Font Awesome.
    "custom_links": {
        "api": [
            {
                "name": "Add Appraisal Report",
                "url": "admin:api_appraisalreport_add",
                "icon": "fas fa-plus",
                "permissions": ["api.add_appraisalreport"]
            },
            {
                "name": "Add Uploaded File",
                "url": "admin:api_uploadedfile_add", "icon": "fas fa-file-upload", "permissions": ["api.add_uploadedfile"]
            }
        ]
    },
}



# --- Email Configuration ---
# Replace with your actual SMTP details.
# For Gmail, you often need to generate an "App Password" in your Google Account Security settings.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'strdjrbservices@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'Strdrjrb@41$'
DEFAULT_FROM_EMAIL = 'STR Team'
