export const ecrSummaryFields = [
  "Client:",
  "Client File #:",
  "Client Address:",
  "Client City:",
  "Client State:",
  "Client Zip Code:",
  "Transferee:",
  "Owner(s) of Record:",
  "Subject Property Address:",
  "Unit:",
  "Subject County:",
  "Subject City:",
  "Subject State:",
  "Subject Zip Code:",
  "Appraiser Company Name:",
  "Appraiser File #:",
  "Appraiser(s):",
  "Co-appraiser (if applicable)",
  "Appraiser Address",
  "Appraiser City:",
  "Appraiser State:",
  "Appraiser Zip Code:",
  "Appraiser Ph. #:",
  "Appraiser Fax #:",
  "Appraiser E-mail:",
  "Anticipated Sales Price: $",
  "Assignment Marketing Period:",
  "Appearance:",
  "Date of Value Opinion (Effective Date):",
  "Is the subject property currently listed?",
  "Current List Price: $",
  // "days on market:",
  "Actual Age (Yrs.):",
  "Bedrooms:",
  "Baths:",
  "Gross Living Area:",
  "Overall Historic Price Trend",
  "Current Supply/Demand:",
  "Forecasted Price Trend:",
  "Mandatory Inspections",
  "Adverse Easements/Encroachments",
  "Adverse External Conditions",
  "Adverse Environmental Conditions",
  "Apparent Modifications to Dwelling",
  "Adverse Conditions Requiring Inspections",
  "Recommended Repairs and/or Improvements",
  "New Construction Competition",
  "Distressed Market Competition",
  "Prevalence of Seller Concessions",
  "Adverse Financing Conditions"
];

export const ecrSubjectFields = [
  "Transferee:",
  "Occupant:",
  "Subject Property Address:",
  "Subject Unit:",
  "Subject County:",
  "Subject City:",
  "Subject State:",
  "Subject Zip Code:",
  "Legal Description:",
  "Assessor's Parcel #:",
  "Map Reference:",
  "Property Rights Appraised:",
  "Subtype:",
  "If condominium or cooperative, indicate complex name:",
  "Total No. of Units",
  "No. of Owner-occupied Units:",
  "% of Owner-occupied Units:",
  "Total No. of Floors:",
  "Subject Floor #:",
  "Is the complex complete?",
  "Is market rate financing available?",
  "Is the developer/builder in control of the homeowners association?",
  "Are there any marketability issues?",
  "Comments:",
  "Annual real estate taxes: $",
  "Tax Year:",
  "Data Source:",
  "Are taxes typical?",
  "Monthly HOA Fees: $",
  "Discuss atypical taxes, homeowner association fees and known pending special assessments, and comment on their effect on marketability",
  "Is the subject property currently listed?",
  "Original List Price: $",
  "Current List Price: $",
  "Date of Last Price Revision:",
  "Days-on-market:",
  "Listing Company/Agent:",
  "Ph. #:",
  "Last Sale Date:",
  "Last Sale Price: $",
  "Analyze and discuss any current agreement of sale, option on or listing of the subject property as well as the last three years of sales history. Include complete marketing history, noting price changes and days on market.",
  "Are there any mandatory inspections required by a governmental institution to transfer title?"
];

export const ecrNeighborhoodFields = [
  "Define neighborhood boundaries (may or may not be the same area used for the Market Trends Analysis on pages 4 and 5).",
  "Location Type:",
  "Built Up:",
  "Development Rate:",
  "Change in Present Land Use:",
  "Single Family:",
  "Multi-family:",
  "Commercial:",
  "Industrial:",
  "Condo:",
  "Present Land Use comment",
  "Single-family Price Range: $",
  "to: $",
  "Predominant Price: $",
  "Single-family Age",
  "years to",
  "Predominant Age:",
  "Predominant Occupancy:",
  "Discuss positive and negative neighborhood characteristics impacting the subject property’s marketability (e.g., employment, environmental conditions, external obsolescence, property compatibility, schools, vacancy rates, transportation, etc.).",
  "Overall Neighborhood Appeal Rating:"
];

export const ecrSiteFields = [
  "Dimensions:",
  "Site Area:",
  "Corner Lot",
  "FEMA Special Flood Hazard Area?",
  "Specific Zoning Classification:",
  "Zoning Description:",
  "Is present use permitted by zoning regulations?",
  "Street Access:",
  "Street Maintenance:",
  "Gated",
  "Electric",
  "Gas",
  "Water",
  "San. Sewer:",
  "Topography:",
  "Shape:",
  "View",
  "Landscaping:",
  "Drainage:",
  "Adverse Easements/Encroachments:",
  "Adverse External Conditions:",
  "Adverse Environmental Conditions:",
  "Street Surface:",
  "Driveway Surface:",
  "Alley:",
  "Discuss positive and negative site characteristics impacting the subject property’s marketability (e.g., site utility, conformity, site improvements, leasehold, adverse conditions, etc)",
  "Overall Site Appeal Rating:"
];

export const ecrImprovementsFields = [
  "Existing Construction:",
  "New Construction:",
  "Completed",
  "Year Built",
  "Actual Age (Yrs.):",
  "Effective Age (Yrs.):",
  "Attached:",
  "Detached:",
  "No. of Units",
  "No. of Stories",
  "Manufact. Housing",
  "If yes, type:",
  "Architectural Style",
  "Roofing Material:",
  "Wall Material",
  "Window Type:",
  "Insulated:",
  "Screens:",
  "Storm Sash:",
  "Gutters/Downspouts:",
  "Exterior Amenities",
  "Floor",
  "Walls",
  "Bath Floors",
  "Bath Wainscot",
  "interior amenities",
  "Kitchen Built-ins",
  "Heating Type:",
  "Heating Fuel:",
  "Air Conditioning Central Air:",
  "Air Conditioning Other:",
  "Attic Scuttle:",
  "Attic Drop Stair:",
  "Attic Stairway:",
  "Attic Finished:",
  "Attic Other:",
  "Garage",
  "Garage (Attached, Detached, Built-in:)",
  "Carport",
  "Carport (Attached, Detached, Built-in:)",
  "Car Storage Other",
  "Foundation Material",
  "Slab:",
  "Crawl Space:",
  "Basement:",
  "Sq. Ft",
  "% Finished:",
  "Floor:",
  "Wall:",
  "Ceiling:",
  "Outside Entry:",
  "Sump:",
  "Other:",
  "Adequate:",
  "Relevant Characteristics/Significant Features: Describe and discuss features and improvements affecting marketability. (Only those relevant characteristics affecting the Anticipated Sales Price should be considered in the Significant Features fields on pages 5 and 6.)",
  "Personal Property: Is personal property included in the Anticipated Sales Price?",
  "Living",
  "Dining",
  "Kitchen",
  "Family",
  "Bedrooms",
  "Baths",
  "Other",
  "Rooms",
  "List of Other Rooms",
  "GLA",
  "Basement",
  "Attic",
  "Bedrooms:",
  "Baths:",
  "Gross Living Area: square feet",
  "Evidence of any apparent modifications to dwelling (e.g., additions, enclosures, etc.):",
  "Evidence of any adverse conditions requiring inspections (e.g., dampness, termites, settlement, etc.):",
  "Discuss evidence of any apparent modifications and/or adverse conditions and list any recommended inspections and why (e.g., structural, materials, mechanical, roof, code compliance, etc.).",
  "Subject Property’s Appearance:",
  "Comments:",
  "Are any repairs and/or improvements recommended?",
  "List recommended repairs and/or Improvements and provide a total estimated cost to cure. Comment on the impact on marketability.",
  "Total Estimated Cost to Cure: $",
  "Exterior Appeal",
  "Quality of Construction",
  "Condition",
  "Interior Appeal/Décor",
  "Functional Utility"
];

export const ecrMarketTrendsFields = [
  "Market Segment: Define the specific market segment (the area in which potential buyers for the subject property may look for substitute properties) and identify the data source used for the market trends data collection and analysis. Utilize geographic, economic or price range criteria to define your market segment. (In order to obtain a dependable quantity of data for analysis, the defined market segment may be different from the subject property’s neighborhood as defined on page 2)",
  "New Construction Competition:",
  "Adverse Financing Conditions:",
  "Distressed Market Competition:",
  "Mortgage Interest Rates:",
  "Prevalence of Seller Concessions:",
  "Comments",
  "Appraiser Defined Time Period",
  "No. of Months",
  "Total No. of Closed Sales",
  "Monthly Absorption Rate",
  "Sales Price",
  "Days on Market",
  "Historic Trends",
  "Analyze and discuss the above trends relevant to developing the Market Change Adjustment in the Sales Comparison Analysis grid on page 6. Discuss the relevance and reliability of the data and any other factors used to determine historic price trends – e.g., sale and resale data.",
  "Overall Historic Price Trend:",
  "CURRENT LISTINGS - Total No. of Active Listings",
  "CURRENT LISTINGS - List Price",
  "CURRENT LISTINGS - Days on Market",
  "CURRENT LISTINGS - Other:",
  "PENDING SALES - Total No. of Active Listings",
  "PENDING SALES - List Price",
  "PENDING SALES - Days on Market",
  "PENDING SALES - Other:",
  "Supply/Demand - Appraiser Defined Time Period",
  "Supply/Demand - No. of Months",
  "Supply/Demand - Total No. of Closed Sales",
  "Supply/Demand - Monthly Absorption Rate",
  "Supply/Demand - Total No. of Active Listings (exclude pending sales)",
  "Supply/Demand - No. of Months Supply of Inventory",
  "Analyze and discuss the above data (consider seasonal influences, pending sales, expired/withdrawn listings, relevance and reliability of data, etc.) that pertains to current supply/demand in the subject property’s market segment.",
  "Current Supply/Demand Status:",
  "Competing Property - Address",
  "Competing Property - Proximity to Subject",
  "Competing Property - Original List Price",
  "Competing Property - Current List Price",
  "Competing Property - Last Price Revision Date",
  "Competing Property - Days on Market",
  "Competing Property - Last Sale Date/Price",
  "Competing Property - Site Area",
  "Competing Property - Site Appeal",
  "Competing Property - Actual Age (Years)",
  "Competing Property - Condition",
  "Competing Property - Rooms",
  "Competing Property - Gross Living Area",
  "Competing Property - GLA Data Source",
  "Competing Property - Basement Area",
  "Competing Property - Car Storage",
  "Competing Property - Significant Features",
  "Competing Property - Comparative Rating to Subject",
  "For each Competing Property, specifically discuss the following: 1) Why was the property selected? 2) What are the major differences between the property and the subject? Comments should support the Comparative Rating to Subject above.",
  "Competing Property #1:",
  "Competing Property #2",
  "Competing Property #3:",
  "Is the subject property realistically priced to sell within the assignment marketing period?",
  "Identify which competing property is positioned to sell first and why. Include the subject property, if listed. Provide support for the competitive list price range below.",
  "Competitive List Price Range for Subject Property (to achieve a sale within the Assignment Marketing Period):",
  "Market Segment Normal Marketing Time:",
  "Subject Property’s Estimated Normal Marketing Time:",
  "Assignment Marketing Period:",
  "Market Segment – Forecasted Trends and Analysis",
  "Forecasted Price Trend",
  "If increasing or decreasing, the Forecasted Price Trend is anticipated to continue at:",
  "Forecasted Sales Activity (not to exceed 120 days or as instructed by client):",
  "Forecasting Adjustment Analysis: Discuss the Historic Trends and Current Factors from pages 4 and 5 and any additional pertinent data relevant to developing the Forecasting Adjustment on page 6. Analyze the anticipated trend of market conditions and prices during the subject property’s assignment marketing period (e.g., mood of the market, seasonal market trends, economic and employment shifts, demographic trends, buyer profile, etc.). This discussion should explain and support the Forecasting Adjustment on page 6",
  "Forecasting:"
];

export const ecrSalesGridAttributes = [
  "Address",
  "Proximity to Subject",
  "Original List Price",
  "Orig. Sales-to-list Price Ratio",
  "Current & Final List Price",
  "Final Sales-to-list Price Ratio",
  "Sales Price",
  "Closing Date",
  "Days on Market",
  "Last Sale Date/Price",
  "Data Verification Sources",
  "Financing Type",
  "Concessions",
  "Market Change Adjustment*",
  "Neighborhood Appeal",
  "Site Area",
  "Site Appeal",
  "Arch. Style/Exterior Appea",
  "Quality of Construction",
  "Actual Age (Years)",
  "Condition",
  "Interior Appeal/Décor",
  "Bdrms",
  "Baths",
  "Gross Living Area",
  "GLA Data Source",
  "Basement Area",
  "Basement Finish",
  "Functional Utility",
  "Heating/Cooling",
  "Car Storage",
  "Fireplace(s)",
  "Significant Features",
  "Forecasting Adjustment**",
  "Net Adjustment",
  "Adjusted Sales Price"
];

export const ecrSalesGridNarrativeFields = [
  "Discuss each comparable sale and explain subjective adjustments for which the rationale may not be readily apparent.",
  "Comparable Sale #1:",
  "Comparable Sale #2",
  "Comparable Sale #3:",
  "Comparable Sale #4:",
  "Comparable Sale #5",
  "Comparable Sale #6:",
  "Did the transferee provide any information for consideration?",
  "Reconciliation (discuss the specific reasoning supporting your opinion of Anticipated Sales Price)"
];

export const ecrComparableSalesList = [
  "COMPARABLE SALE #1",
  "COMPARABLE SALE #2",
  "COMPARABLE SALE #3",
  "COMPARABLE SALE #4",
  "COMPARABLE SALE #5",
  "COMPARABLE SALE #6"
];

export const ecrSalesGridRows = ecrSalesGridAttributes.map(attr => ({
  label: attr,
  valueKey: attr,
  adjustmentKey: (attr === 'Market Change Adjustment*' || attr === 'Forecasting Adjustment**' || attr === 'Net Adjustment') ? attr : null
}));

export const ecrSalesComparisonFields = [
  ...ecrSalesGridAttributes,
  ...ecrSalesGridNarrativeFields
];

export const ecrAnticipatedSalesPriceFields = [
  "Is the Subject Property currently listed?",
  "Current List Price: $",
  "Competitive List Price Range for Subject Property (to achieve a sale within the Assignment Marketing Period): $",
  "Assignment Marketing Period:",
  "Subject Property’s Appearance",
  "Opinion of Anticipated Sales Price as of ____ is $______________",
  "Transferee",
  "Appraiser"
];

export const ecrCertificationFields = [
  "Subject Property Address",
  "Subject Unit:",
  "Subject County:",
  "Subject City:",
  "Subject State:",
  "Subject Zip Code:",
  "APPRAISER Signature:",
  "APPRAISER Name:",
  "Date of Appraisal Inspection:",
  "Date of Value Opinion (Effective Date):",
  "State License/Certification #:",
  "State of License/Certification",
  "Expiration Date of License/Certification:",
  "CO-APPRAISER (if applicable) Signature:",
  "CO-APPRAISER Name",
  "CO-APPRAISER Date of Appraisal Inspection:",
  "CO-APPRAISER Date of Value Opinion (Effective Date)",
  "CO-APPRAISER State License/Certification #:",
  "CO-APPRAISER State of License/Certification:",
  "CO-APPRAISER Expiration Date of License/Certification:",
  "Did Did Not personally inspect the subject property."
];

export const ecrAllSectionFieldsMap = {
  'SUMMARY': ecrSummaryFields,
  'SUBJECT': ecrSubjectFields,
  'NEIGHBORHOOD': ecrNeighborhoodFields,
  'SITE': ecrSiteFields,
  'IMPROVEMENTS': ecrImprovementsFields,
  'MARKET_TRENDS': ecrMarketTrendsFields,
  'SALES_COMPARISON': ecrSalesComparisonFields,
  'ANTICIPATED_SALES_PRICE': ecrAnticipatedSalesPriceFields,
  'CERTIFICATION': ecrCertificationFields
};
